name: qiu-lianjie

on:
  workflow_dispatch:
    inputs:
      search_query:
        description: 'Enter tiktok Search Query'
        required: true
        default: 'site:tiktok.com intext:( "link please" OR "where to buy" OR "where can I find" OR "where did you get this" OR "what is it called" OR "drop the link" OR "pls link" OR "can i get the link" OR "what"s the link" OR "link to buy" OR "source?" OR "where can i find it?" OR "where can i get it?" OR "product recs?" OR "product recommendations?" OR "what brand is it?" OR "what brand?" OR "where"s it from?" OR "link in comments")'  # PREDEFINED QUERY
      timeframe:
        description: 'Enter tiktok Search timeframe'
        required: true
        default: 'qdr:h1'

jobs:
  search_and_commit:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google pandas requests

      # Run the Python script with the input query
      - name: Run Google Search script
        run: |
          python google_search_qdr.py "${{ github.event.inputs.search_query }}" "${{github.event.inputs.timeframe}}"

      # Commit and push the result CSV file to the repository
      - name: Commit CSV file with search results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Add search results for query: ${{ github.event.inputs.search_query }}"
          git push
